### ISSUE TITLE
Output Range 

### ISSUE THREAD

**Issue by onurjuzelle** [thibDev/mTSP#1]
For the mono objective part, is there a way to customize the code to output to only print the solutions, for example only algorithm keeps calculation until the distance is below 34000

**Comment by ThiBsc** [comment]
Sure, it's possible. Can you give me more precision to be sure about what you want ? Give example input and wanted output.

**Comment by onurjuzelle** [comment]
So the algorithm generates different solutions every time it's executed. I want to customize in a way that the it only prints the best solution it could compute. This is the input i am processing.
[Input.txt](https://github.com/ThiBsc/mTSP/files/4641233/Input.txt)

**Comment by ThiBsc** [comment]
The traveling salesman problem is a hard problem. The 2-Opt operator used is not a method that give the best solution. It's give one of a good solution with adequate waiting time. But a possible solution is to execute until reach a wanted cost. But keep in mind, by this way, the solution can take a very long time. Is what you want ?

**Comment by ThiBsc** [comment]
> So the algorithm generates different solutions every time it's executed. I want to customize in a way that the it only prints the best solution it could compute. This is the input i am processing.
> [Input.txt](https://github.com/ThiBsc/mTSP/files/4641233/Input.txt)

The traveling salesman problem is a hard problem. The 2-Opt operator used is not a method that give the best solution. It gives one of a good solution with adequate waiting time. But a possible solution is to execute until reach a wanted cost. But keep in mind, by this way, the solution can take a very long time, and if no solution exist with the wanted cost, it will never finish. Is it what you want ?

**Comment by onurjuzelle** [comment]
Yeah, pretty much it is. I wanna be able to define a range of acceptable solutions, path distance under a certain number. Not an exact number but a range to there is more room for the algorithm. This way running time won't get affected as much as it would if it was an exact number to the solution desired.

**Comment by ThiBsc** [comment]
> Yeah, pretty much it is. I wanna be able to define a range of acceptable solutions, path distance under a certain number. Not an exact number but a range to there is more room for the algorithm. This way running time won't get affected as much as it would if it was an exact number to the solution desired.

Ok so I can add an optional third parameter for the mono-objective to stop when a solution with a lower cost than the parameter is found. But if your parameter is too low, it will never stop. I add this feature ?

**Comment by onurjuzelle** [comment]
It would be appreciated! Thanks a lot, i tried to do it on my own but just couldn't.

**Comment by ThiBsc** [comment]
> It would be appreciated! Thanks a lot, i tried to do it on my own but just couldn't.

Not a problem, I add this, just wait a moment

**Comment by ThiBsc** [comment]
@onurjuzelle , tested with your input.txt, I got an answer with a cost `33784`. I change the README and update

**Comment by onurjuzelle** [comment]
> @onurjuzelle , tested with your input.txt, I got an answer with a cost `33784`. I change the README and update

I am not able to see the updates tho. But the answer seems pretty optimal since the shortest path possible with this input is 33523.

**Comment by onurjuzelle** [comment]
j'espère que ces circonstances s'améliorent pour les français. reste en bonne santé bro

**Comment by ThiBsc** [comment]
Tell me if the modification is okay for you and I will close this request ;)

**Comment by ThiBsc** [comment]
Your solution by using `UNDER_LIMIT` parameter with `33600`: cost 33555.3
[solution.txt](https://github.com/ThiBsc/mTSP/files/4641369/sol_mono_objective.txt)

**Comment by onurjuzelle** [comment]
All good, cheers!

**Comment by ThiBsc** [comment]
Hi, sorry to open it 2 years after, but I would like to know if it was for a company or your personal use this modification.
Thank you by advance and have a good weekend 🙂

**Comment by onurjuzelle** [comment]
Hi, no problem at all. I was working on a personal project, I was a student back then :) Have a great weekend!
